// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Categories: typeof import('./components/categories.vue')['default']
    Item_palette: typeof import('./components/item_palette.vue')['default']
    Item_view: typeof import('./components/item_view.vue')['default']
    LocationInput: typeof import('./components/locationInput.vue')['default']
    MapContainer: typeof import('./components/MapContainer.vue')['default']
    Navigation: typeof import('./components/navigation.vue')['default']
    Purchase_window: typeof import('./components/purchase_window.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signin: typeof import('./components/signin.vue')['default']
    Signup: typeof import('./components/signup.vue')['default']
  }
}
